openapi: "3.0.0"

info:
  title: "Text Anonymizer"
  description: "API that accepts a text string and returns an anonymized version of it."
  version: "1.0"

paths:
  /api:
    post:
      description: "Anonymize text"

      requestBody:
        description: "Json with three fields"
        required: true
        content:
          application/json:
            schema:
              type: object 
              properties:
                text:
                  type: string
                entities:
                  type: array
                  description: PERSON  (People, including fictional);
                        NORP (Nationalities or religious or political groups);
                        FAC  (Buildings, airports, highways, bridges, etc.);
                        ORG  (Companies, agencies, institutions, etc.);
                        GPE  (Countries, cities, states);
                        LOC  (Non-GPE locations, mountain ranges, bodies of water);
                        PRODUCT  (Objects, vehicles, foods, etc. (Not services.));
                        EVENT  (Named hurricanes, battles, wars, sports events, etc.);
                        WORK_OF_ART  (Titles of books, songs, etc.);
                        LAW  (Named documents made into laws);
                        LANGUAGE (Any named language);
                        DATE (Absolute or relative dates or periods);
                        TIME (Times smaller than a day);
                        PERCENT  (Percentage, including ”%“);
                        MONEY  (Monetary values, including unit);
                        QUANTITY (Measurements, as of weight or distance);
                        ORDINAL  (“first”, “second”, etc.);
                        CARDINAL (Numerals that do not fall under another type).
                  items:
                    type: string
                fake_names:
                  type: boolean

      responses:
        '200':
          description: "Returns anonymized text"
          content: 
           application/json: {}